/**
 * AutoSaleVPS shortcode initializer for Argon theme with Pjax support
 * 1. Run on first page load
 * 2. Run again after every Pjax navigation (window.pjaxLoaded)
 *
 * REQUIREMENT:
 *   Each [AutoSaleVPS] block in HTML must be wrapped like:
 *   <div class="autosalevps-wrapper" data-autosalevps="1"> ... </div>
 */

/**
 * Main init function for AutoSaleVPS blocks.
 * It will:
 *   - Find all elements with [data-autosalevps="1"]
 *   - Ensure each is initialized only once
 *   - Run your custom front-end logic for each block
 */
function autoSaleVPSInit() {
  // Find all blocks generated by [AutoSaleVPS]
  var vpsBlocks = document.querySelectorAll('[data-autosalevps="1"]');
  if (!vpsBlocks.length) return;

  vpsBlocks.forEach(function (block) {
    // Prevent duplicate initialization on the same DOM element
    if (block.dataset.autosalevpsInited === '1') return;
    block.dataset.autosalevpsInited = '1';

    // ===============================
    // Put your original JS logic here
    // ===============================
    //
    // Example 1: If your plugin exposes a global init function:
    //   if (typeof window.AutoSaleVPSInit === 'function') {
    //     window.AutoSaleVPSInit(block);
    //   }
    //
    // Example 2: Bind some events, timers, etc. on elements inside "block":
    //
    // var buyLinks = block.querySelectorAll('.autosalevps-buy-link');
    // buyLinks.forEach(function (link) {
    //   link.addEventListener('click', function () {
    //     // Track click or do something else
    //     console.log('AutoSaleVPS link clicked:', link.href);
    //   });
    // });
    //
    // If you don't have any special JS now,
    // you can keep this function body empty; it is safe.

  });
}

/**
 * Hook into Argon's Pjax lifecycle:
 *   - If window.pjaxLoaded already exists, keep its original behavior
 *     and then call autoSaleVPSInit()
 *   - If not, define a new window.pjaxLoaded and call autoSaleVPSInit()
 * Also:
 *   - On first page load (DOMContentLoaded), manually call window.pjaxLoaded()
 *     so that autoSaleVPSInit() runs once even without Pjax navigation.
 */
(function () {
  // Save original pjaxLoaded if defined
  var oldPjaxLoaded = typeof window.pjaxLoaded === 'function' ? window.pjaxLoaded : null;

  // Define/redefine window.pjaxLoaded
  window.pjaxLoaded = function () {
    // 1. Run theme's original handler (if any)
    if (typeof oldPjaxLoaded === 'function') {
      try {
        oldPjaxLoaded();
      } catch (e) {
        console.error('Error in original window.pjaxLoaded:', e);
      }
    }

    // 2. Run AutoSaleVPS initializer
    try {
      autoSaleVPSInit();
    } catch (e) {
      console.error('Error in autoSaleVPSInit:', e);
    }
  };

  // First page load: call window.pjaxLoaded() manually
  document.addEventListener('DOMContentLoaded', function () {
    if (typeof window.pjaxLoaded === 'function') {
      try {
        window.pjaxLoaded();
      } catch (e) {
        console.error('Error when calling window.pjaxLoaded on first load:', e);
      }
    } else {
      // Fallback: if for some reason pjaxLoaded is not defined,
      // at least run autoSaleVPSInit() once.
      try {
        autoSaleVPSInit();
      } catch (e) {
        console.error('Error in autoSaleVPSInit (fallback first load):', e);
      }
    }
  });
})();